
#ifndef EFM32_DMA_SOURCE_H_
#define EFM32_DMA_SOURCE_H_

#define EFM32_DMA_SOURCE_NONE     0
#define EFM32_DMA_SOURCE_ADC0     8
#define EFM32_DMA_SOURCE_USART1   13
#define EFM32_DMA_SOURCE_LEUART0  16
#define EFM32_DMA_SOURCE_I2C0     20
#define EFM32_DMA_SOURCE_TIMER0   24
#define EFM32_DMA_SOURCE_TIMER1   25
#define EFM32_DMA_SOURCE_MSC      48
#define EFM32_DMA_SOURCE_AES      49

#define EFM32_DMA_SIGNAL_ADC0SINGLE         0
#define EFM32_DMA_SIGNAL_ADC0SCAN           1

#define EFM32_DMA_SIGNAL_USART1RXDATAV      0
#define EFM32_DMA_SIGNAL_USART1TXBL         1
#define EFM32_DMA_SIGNAL_USART1TXEMPTY      2
#define EFM32_DMA_SIGNAL_USART1RXDATAVRIGHT 3
#define EFM32_DMA_SIGNAL_USART1TXBLRIGHT    4

#define EFM32_DMA_SIGNAL_LEUART0RXDATAV     0
#define EFM32_DMA_SIGNAL_LEUART0TXBL        1
#define EFM32_DMA_SIGNAL_LEUART0TXEMPTY     2

#define EFM32_DMA_SIGNAL_I2C0RXDATAV        0
#define EFM32_DMA_SIGNAL_I2C0TXBL           1

#define EFM32_DMA_SIGNAL_TIMER0UFOF         0
#define EFM32_DMA_SIGNAL_TIMER0CC0          1
#define EFM32_DMA_SIGNAL_TIMER0CC1          2
#define EFM32_DMA_SIGNAL_TIMER0CC2          3

#define EFM32_DMA_SIGNAL_TIMER1UFOF         0
#define EFM32_DMA_SIGNAL_TIMER1CC0          1
#define EFM32_DMA_SIGNAL_TIMER1CC1          2
#define EFM32_DMA_SIGNAL_TIMER1CC2          3

#define EFM32_DMA_SIGNAL_MSCWDATA           0

#define EFM32_DMA_SIGNAL_AESDATAWR          0
#define EFM32_DMA_SIGNAL_AESXORDATAWR       1
#define EFM32_DMA_SIGNAL_AESDATARD          2
#define EFM32_DMA_SIGNAL_AESKEYWR           2

#endif

