objs += socket.o inet.o
objs-$(CONFIG_NETWORK_UDP) += socket_udp.o
objs-$(CONFIG_NETWORK_TCP) += socket_tcp.o
objs-$(CONFIG_NETWORK_SOCKET_PACKET) += socket_packet.o
objs-$(CONFIG_NETWORK_SOCKET_RAW) += socket_raw.o

