
DIR_CFLAGS = -D_HEXO_INTTYPES_DEPRECATED

doc_headers = crypto/crypto.h crypto/arc4.h crypto/crc32.h

objs-$(CONFIG_LIBCRYPTO_ARC4) += arc4.o
objs-$(CONFIG_LIBCRYPTO_CRC32) += crc32.o
objs-$(CONFIG_LIBCRYPTO_MD5) += md5.o
