
ifeq ($(CONFIG_DRIVER_CHAR_RANDOM), defined)
 subdirs += random
endif

ifeq ($(CONFIG_DRIVER_CHAR_ZERO), defined)
 subdirs += zero
endif

ifeq ($(CONFIG_DRIVER_CHAR_NULL), defined)
 subdirs += null
endif

ifeq ($(CONFIG_DRIVER_CHAR_CADENCE_UART), defined)
 subdirs += cadence_uart
endif

