subdirs-$(CONFIG_DRIVER_CHAR_RANDOM) += random
subdirs-$(CONFIG_DRIVER_CHAR_RTT) += rtt
subdirs-$(CONFIG_DRIVER_CHAR_ZERO) += zero
subdirs-$(CONFIG_DRIVER_CHAR_NULL) += null
subdirs-$(CONFIG_DRIVER_CHAR_CADENCE_UART) += cadence_uart
subdirs-$(CONFIG_DRIVER_CHAR_MUX) += mux
subdirs-$(CONFIG_DRIVER_CHAR_PIPE) += pipe
subdirs-$(CONFIG_DRIVER_CHAR_USBDEV_ACM) += usbdev_acm
