
ifeq ($(CONFIG_DRIVER_ICU_8259), defined)
 subdirs += 8259
endif

ifeq ($(CONFIG_DRIVER_ICU_SOCLIB), defined)
 subdirs += soclib
endif

ifeq ($(CONFIG_DRIVER_ICU_MIPS), defined)
 subdirs += mips
endif

ifeq ($(CONFIG_DRIVER_ICU_PPC), defined)
 subdirs += ppc
endif

ifeq ($(CONFIG_DRIVER_ICU_ARM), defined)
 subdirs += arm
endif

