
ifeq ($(CONFIG_CPU_MIPS), defined)
objs = test_mips.o
endif

ifeq ($(CONFIG_CPU_PPC), defined)
objs = test_ppc.o
endif

ifeq ($(CONFIG_CPU_ARM32), defined)
objs = test_arm32.o
endif

ifeq ($(CONFIG_CPU_ARM32M), defined)
objs = test_arm32m.o
endif

ifeq ($(CONFIG_CPU_LM32), defined)
objs = test_lm32.o
endif

ifeq ($(CONFIG_CPU_NIOS2), defined)
objs = test_nios2.o
endif

ifeq ($(CONFIG_CPU_SPARC), defined)
objs = test_sparc.o
endif

ifeq ($(CONFIG_CPU_X86), defined)
objs = test_x86.o
endif

