subdirs-$(CONFIG_DRIVER_CC26XX_UART) += uart
subdirs-$(CONFIG_DRIVER_CC26XX_GPIO) += gpio
subdirs-$(CONFIG_DRIVER_CC26XX_TIMER) += timer
subdirs-$(CONFIG_DRIVER_CC26XX_RTC) += rtc
subdirs-$(CONFIG_DRIVER_CC26XX_SPI) += spi
