objs = 											\
stdio.o											\
string.o										\
alloc.o											\
intconv.o										\
printf.o										\
rand.o											\
timer.o

ifeq ($(CONFIG_LIBC_SEMAPHORE), defined)
objs += sem.o
endif


