        .section .pic32fuses,"ax",@progbits

        /* PIC32MZ configuration bits, see manual */
        .word 0xffff1234
        .word 0xffffffff
        .word 0xff7fffff
        .word 0xffffffff
        .word 0xffffffff
        .word 0xffffffff
        .word 0xffffffff
        .word 0xffffffff
        .word 0xffffffff
        .word 0xffffffff
        .word 0xffffffff
        .word 0xffffffff
        .word 0xffffffff
        .word 0xffffffff
        .word 0xffffffff
        .word 0xffffffff
        .word 0xffffffff
        .word 0xffffffff
        .word 0xffffffff
        .word 0xffffffff
        .word 0xffffffff
        .word 0xffffffff
        .word 0xffffffff
        .word 0xffffffff
        .word 0xffffffff
        .word 0xffffffff
        .word 0xffffffff
        .word 0xffffffff
        .word 0xffffffff
        .word 0xffffffff
        .word 0xffffffff
        .word 0xffffffff
        .word 0xbfffffff  #DEVCFG3
        .word 0xfffc3f98  #DEVCFG2
        .word 0x7f737839  #DEVCFG1
        .word 0xffffcfd6  #DEVCFG0
        .word 0xffffffff
        .word 0xffffffff
        .word 0xffffffff
        .word 0xffffffff
