/***************************************
* Auto generated by BFGen, do not edit *
***************************************/

/*
   bfgen -I peri.bf -O peri.h -o cdefs cdefs_use_reg_mask=1                    \
     cdefs_use_field_setval=1
*/

#ifndef _PERI_BFGEN_DEFS_
#define _PERI_BFGEN_DEFS_

#define PERI_DIV_CMD_ADDR                            0x00000000
#define PERI_DIV_CMD_MASK                            0xc000ffff
/** Specifies the divider type/number pair of the divider. @multiple */
  #define PERI_DIV_CMD_SEL(v)                      ((v) << 0)
  #define PERI_DIV_CMD_SEL_SET(x, v)               do { (x) = (((x) & ~0xff) | ((v) << 0)); } while(0)
  #define PERI_DIV_CMD_SEL_GET(x)                  (((x) >> 0) & 0xff)
/** Specifies the divider type/number pair of the divider to which phase
   alignment is performed for the clock enable command. @multiple */
  #define PERI_DIV_CMD_PA_SEL(v)                   ((v) << 8)
  #define PERI_DIV_CMD_PA_SEL_SET(x, v)            do { (x) = (((x) & ~0xff00) | ((v) << 8)); } while(0)
  #define PERI_DIV_CMD_PA_SEL_GET(x)               (((x) >> 8) & 0xff)
/** Clock divider disable command @multiple */
  #define PERI_DIV_CMD_DISABLE                     0x40000000
/** Clock divider enable command @multiple */
  #define PERI_DIV_CMD_ENABLE                      0x80000000

#define PERI_PCLK_CTL_ADDR(ridx)                     (0x00000100 + (ridx) * 4)
#define PERI_PCLK_CTL_COUNT                          16
#define PERI_PCLK_CTL_MASK                           0x000000ff
/** Specifies divider @multiple */
  #define PERI_PCLK_CTL_SEL(v)                     ((v) << 0)
  #define PERI_PCLK_CTL_SEL_SET(x, v)              do { (x) = (((x) & ~0xff) | ((v) << 0)); } while(0)
  #define PERI_PCLK_CTL_SEL_GET(x)                 (((x) >> 0) & 0xff)

#define PERI_DIV_CTL_ADDR(ridx)                      (0x00000200 + (ridx) * 4)
#define PERI_DIV_CTL_COUNT                           64
#define PERI_DIV_CTL_MASK                            0xfffffff9
/** Divider enabled. This bit is restored when device gets out of sleep.
   @multiple */
  #define PERI_DIV_CTL_EN                          0x00000001
/** Divisor in 1/64 steps, minus 1 @multiple */
  #define PERI_DIV_CTL_DIV(v)                      ((v) << 3)
  #define PERI_DIV_CTL_DIV_SET(x, v)               do { (x) = (((x) & ~0xfffffff8) | ((v) << 3)); } while(0)
  #define PERI_DIV_CTL_DIV_GET(x)                  (((x) >> 3) & 0x1fffffff)

#endif

