/***************************************
* Auto generated by BFGen, do not edit *
***************************************/

/*
   bfgen -I tcpwm.bf -O tcpwm.h -o cdefs cdefs_use_reg_mask=1                  \
     cdefs_use_field_setval=1
*/

#ifndef _TCPWM_BFGEN_DEFS_
#define _TCPWM_BFGEN_DEFS_

#define TCPWM_TCPWM_CTRL_ADDR                        0x00000000
#define TCPWM_TCPWM_CTRL_MASK                        0x0000000f
/** Counter enable. @multiple */
  #define TCPWM_TCPWM_CTRL_COUNTER_ENABLED_COUNT   4
  #define TCPWM_TCPWM_CTRL_COUNTER_ENABLED(fidx)   (0x00000001 << ((fidx)))

#define TCPWM_TCPWM_CMD_ADDR                         0x00000008
#define TCPWM_TCPWM_CMD_MASK                         0x0f0f0f0f
/** Counter capture trigger @multiple */
  #define TCPWM_TCPWM_CMD_COUNTER_CAPTURE_COUNT    4
  #define TCPWM_TCPWM_CMD_COUNTER_CAPTURE(fidx)    (0x00000001 << ((fidx)))
/** Counter reload trigger @multiple */
  #define TCPWM_TCPWM_CMD_COUNTER_RELOAD_COUNT     4
  #define TCPWM_TCPWM_CMD_COUNTER_RELOAD(fidx)     (0x00000100 << ((fidx)))
/** Counter stop trigger @multiple */
  #define TCPWM_TCPWM_CMD_COUNTER_STOP_COUNT       4
  #define TCPWM_TCPWM_CMD_COUNTER_STOP(fidx)       (0x00010000 << ((fidx)))
/** Counter start trigger @multiple */
  #define TCPWM_TCPWM_CMD_COUNTER_START_COUNT      4
  #define TCPWM_TCPWM_CMD_COUNTER_START(fidx)      (0x01000000 << ((fidx)))

#define TCPWM_TCPWM_INTR_CAUSE_ADDR                  0x0000000c
#define TCPWM_TCPWM_INTR_CAUSE_MASK                  0x0000000f
/** Counters interrupt signal active @multiple */
  #define TCPWM_TCPWM_INTR_CAUSE_COUNTER_INT_COUNT 4
  #define TCPWM_TCPWM_INTR_CAUSE_COUNTER_INT(fidx) (0x00000001 << ((fidx)))

#endif

