/***************************************
* Auto generated by BFGen, do not edit *
***************************************/

/*
   bfgen -I tst.bf -O tst.h -o cdefs cdefs_use_reg_mask=1                      \
     cdefs_use_field_setval=1
*/

#ifndef _TST_BFGEN_DEFS_
#define _TST_BFGEN_DEFS_

#define TST_MODE_ADDR                                0x00000014
#define TST_MODE_MASK                                0xc0000004
/** Whether SWD activated (Line Reset & Connect sequence passed) @multiple */
  #define TST_MODE_SWD_CONNECTED                   0x00000004
/** This bit is set during POR bypass mode. When this bit is set, the BootROM
   will not yield execu- tion to the FLASH image (same function as setting
   TEST_MODE bit below). @multiple */
  #define TST_MODE_POR_BYPASS                      0x40000000
/** Setting this bit will prevent BootROM from yielding execution to Flash image.
   @multiple */
  #define TST_MODE_TEST_MODE                       0x80000000

#endif

