
@node Integer types, Endian and alignment, , Hexo API
@section Integer types
@include c_hexo_api/types.texi

@node Endian and alignment, System startup, Integer types, Hexo API
@section Endian and alignment
@include c_hexo_api/endian.texi

@node System startup, Atomic integer access, Endian and alignment, Hexo API
@section System startup
@include c_hexo_api/init.texi

@node Atomic integer access, Spinlocks, System startup, Hexo API
@section Atomic integer access
@include c_hexo_api/atomic.texi

@node Spinlocks, Memory allocation, Atomic integer access, Hexo API
@section Spinlocks
@include c_hexo_api/lock.texi

@node Memory allocation, Processor and context local data, Spinlocks, Hexo API
@section  Memory allocation
@c alloc.h segment.h
@include c_hexo_api/memory_allocation.texi

@node Processor and context local data, IO Space access, Memory allocation, Hexo API
@section Processor and context local variables
@include c_hexo_api/local.texi

@node IO Space access, Processor events, Processor and context local data, Hexo API
@section IO Space access
@include c_hexo_api/iospace.texi

@node Processor events,  Processor specific features, IO Space access, Hexo API
@section Processor events
@include c_hexo_api/interrupts.texi

@node Processor specific features, Running contexts management, Processor events, Hexo API
@section Processor specific features
@include c_hexo_api/cpu.texi

@node Running contexts management, Generic contexts scheduler,  Processor specific features, Hexo API
@section Running contexts management
@include c_hexo_api/context.texi

@node Generic contexts scheduler,  , Running contexts management, Hexo API
@section Generic contexts scheduler
@include c_hexo_api/sheduler.texi

