
@node System startup, Integer types, , Hexo API
@section System startup
@include c_hexo_api/init.texi

@page
@node Integer types, Endian and alignment, System startup, Hexo API
@section Integer types
@include c_hexo_api/types.texi

@page
@node Endian and alignment, Atomic memory access, Integer types, Hexo API
@section Endian and alignment
@include c_hexo_api/endian.texi

@page
@node Atomic memory access, Spinlocks, System startup, Hexo API
@section Atomic memory access
@include c_hexo_api/atomic.texi

@page
@node Spinlocks, Memory allocation, Atomic memory access, Hexo API
@section Spinlocks
@include c_hexo_api/lock.texi

@page
@node Memory allocation, Processor and context local data, Spinlocks, Hexo API
@section  Memory allocation
@c alloc.h segment.h
@include c_hexo_api/memory_allocation.texi

@page
@node Processor and context local data, IO Space access, Memory allocation, Hexo API
@section Processor and context local variables
@include c_hexo_api/local.texi

@page
@node IO Space access, Processor events, Processor and context local data, Hexo API
@section IO Space access
@include c_hexo_api/iospace.texi

@page
@node Processor events,  Miscellaneous processor functions, IO Space access, Hexo API
@section Processor events
@include c_hexo_api/interrupts.texi

@page
@node Miscellaneous processor functions, Execution contexts management, Processor events, Hexo API
@section Miscellaneous processor functions
@include c_hexo_api/cpu.texi

@page
@node Execution contexts management, Contexts scheduler,  Miscellaneous processor functions, Hexo API
@section Execution contexts management
@include c_hexo_api/context.texi

@page
@node Contexts scheduler,  , Execution contexts management, Hexo API
@section Contexts scheduler
@include c_hexo_api/sheduler.texi

