objs += clock.o
objs-$(CONFIG_DRIVER_PSOC4_PRINTK) += printk.o
objs-$(CONFIG_DRIVER_PSOC4_UART) += uart.o
objs-$(CONFIG_DRIVER_PSOC4_GPIO) += gpio.o
objs-$(CONFIG_DRIVER_PSOC4_RTC) += rtc.o
objs-$(CONFIG_DRIVER_PSOC4_BLE) += ble.o
