/*
    This file is part of MutekH.

    MutekH is free software; you can redistribute it and/or modify it
    under the terms of the GNU Lesser General Public License as
    published by the Free Software Foundation; version 2.1 of the
    License.

    MutekH is distributed in the hope that it will be useful, but
    WITHOUT ANY WARRANTY; without even the implied warranty of
    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
    Lesser General Public License for more details.

    You should have received a copy of the GNU Lesser General Public
    License along with this program.  If not, see
    <http://www.gnu.org/licenses/>.

    Copyright Nicolas Pouillon <nipo@ssji.net> (c) 2015
*/

#ifndef BLE_PROTOCOL_SERVICES_H
#define BLE_PROTOCOL_SERVICES_H

#define BLE_GATT_SERVICE_ALERT_NOTIFICATION 0x1811
#define BLE_GATT_SERVICE_BATTERY 0x180F
#define BLE_GATT_SERVICE_BLOOD_PRESSURE 0x1810
#define BLE_GATT_SERVICE_BODY_COMPOSITION 0x181B
#define BLE_GATT_SERVICE_BOND_MANAGEMENT 0x181E
#define BLE_GATT_SERVICE_CONTINUOUS_GLUCOSE_MONITORING 0x181F
#define BLE_GATT_SERVICE_CURRENT_TIME 0x1805
#define BLE_GATT_SERVICE_CYCLING_POWER 0x1818
#define BLE_GATT_SERVICE_CYCLING_SPEED_AND_CADENCE 0x1816
#define BLE_GATT_SERVICE_DEVICE_INFORMATION 0x180A
#define BLE_GATT_SERVICE_ENVIRONMENTAL_SENSING 0x181A
#define BLE_GATT_SERVICE_GENERIC_ACCESS 0x1800
#define BLE_GATT_SERVICE_GENERIC_ATTRIBUTE 0x1801
#define BLE_GATT_SERVICE_GLUCOSE 0x1808
#define BLE_GATT_SERVICE_HEALTH_THERMOMETER 0x1809
#define BLE_GATT_SERVICE_HEART_RATE 0x180D
#define BLE_GATT_SERVICE_HUMAN_INTERFACE_DEVICE 0x1812
#define BLE_GATT_SERVICE_IMMEDIATE_ALERT 0x1802
#define BLE_GATT_SERVICE_INDOOR_POSITIONING 0x1821
#define BLE_GATT_SERVICE_INTERNET_PROTOCOL_SUPPORT 0x1820
#define BLE_GATT_SERVICE_LINK_LOSS 0x1803
#define BLE_GATT_SERVICE_LOCATION_AND_NAVIGATION 0x1819
#define BLE_GATT_SERVICE_NEXT_DST_CHANGE 0x1807
#define BLE_GATT_SERVICE_PHONE_ALERT_STATUS 0x180E
#define BLE_GATT_SERVICE_REFERENCE_TIME_UPDATE 0x1806
#define BLE_GATT_SERVICE_RUNNING_SPEED_AND_CADENCE 0x1814
#define BLE_GATT_SERVICE_SCAN_PARAMETERS 0x1813
#define BLE_GATT_SERVICE_TX_POWER 0x1804
#define BLE_GATT_SERVICE_USER_DATA 0x181C
#define BLE_GATT_SERVICE_WEIGHT_SCALE 0x181D

#endif
