
objs = 

ifeq ($(CONFIG_MUTEK_MAIN), defined)
 objs += main.o
endif

ifeq ($(CONFIG_MUTEK_LOGO), defined)
 objs += mutek_logo_320x200.o
endif

ifeq ($(CONFIG_MUTEK_SCHEDULER), defined)
objs += scheduler.o
endif

ifeq ($(CONFIG_MUTEK_RWLOCK), defined)
objs += rwlock.o
endif

