#ifndef EFM32_DMA_SOURCE_H_
#define EFM32_DMA_SOURCE_H_

#define EFM32_DMA_SOURCE_NONE     0
#define EFM32_DMA_SOURCE_PRS      1
#define EFM32_DMA_SOURCE_ADC0     8
#define EFM32_DMA_SOURCE_USART0   12
#define EFM32_DMA_SOURCE_USART1   13
#define EFM32_DMA_SOURCE_USART2   14
#define EFM32_DMA_SOURCE_USART3   15
#define EFM32_DMA_SOURCE_LEUART0  16
#define EFM32_DMA_SOURCE_I2C0     20
#define EFM32_DMA_SOURCE_TIMER0   24
#define EFM32_DMA_SOURCE_TIMER1   25
#define EFM32_DMA_SOURCE_MSC      48
#define EFM32_DMA_SOURCE_CRYPTO   49

#define EFM32_DMA_SIGNAL_ADC0SINGLE         0
#define EFM32_DMA_SIGNAL_ADC0SCAN           1

#define EFM32_DMA_SIGNAL_PRSREQ0            0
#define EFM32_DMA_SIGNAL_PRSREQ1            1

#define EFM32_DMA_SIGNAL_USARTRXDATAV      0
#define EFM32_DMA_SIGNAL_USARTTXBL         1
#define EFM32_DMA_SIGNAL_USARTTXEMPTY      2
#define EFM32_DMA_SIGNAL_USARTRXDATAVRIGHT 3
#define EFM32_DMA_SIGNAL_USARTTXBLRIGHT    4

#define EFM32_DMA_SIGNAL_LEUARTRXDATAV     0
#define EFM32_DMA_SIGNAL_LEUARTTXBL        1
#define EFM32_DMA_SIGNAL_LEUARTTXEMPTY     2

#define EFM32_DMA_SIGNAL_I2CRXDATAV        0
#define EFM32_DMA_SIGNAL_I2CTXBL           1

#define EFM32_DMA_SIGNAL_TIMERUFOF         0
#define EFM32_DMA_SIGNAL_TIMERCC0          1
#define EFM32_DMA_SIGNAL_TIMERCC1          2
#define EFM32_DMA_SIGNAL_TIMERCC2          3

#define EFM32_DMA_SIGNAL_MSCWDATA           0

#define EFM32_DMA_SIGNAL_CRYPTDATA0WR      0
#define EFM32_DMA_SIGNAL_CRYPTXORDATA0XWR  1
#define EFM32_DMA_SIGNAL_CRYPTDATA0RD      2
#define EFM32_DMA_SIGNAL_CRYPTDATA1WR      3
#define EFM32_DMA_SIGNAL_CRYPTDATA1RD      4

#endif

