subdirs-$(CONFIG_DRIVER_GAISLER_APBUART) += apbuart
subdirs-$(CONFIG_DRIVER_GAISLER_AHBCTRL) += ahbctrl
subdirs-$(CONFIG_DRIVER_GAISLER_APBCTRL) += apbctrl
subdirs-$(CONFIG_DRIVER_GAISLER_IRQMP) += irqmp
subdirs-$(CONFIG_DRIVER_GAISLER_GPTIMER) += gptimer
subdirs-$(CONFIG_DRIVER_GAISLER_GRETH) += greth
