
ifeq ($(CONFIG_DRIVER_GAISLER_APBUART), defined)
subdirs += apbuart
endif

ifeq ($(CONFIG_DRIVER_GAISLER_AHBCTRL), defined)
subdirs += ahbctrl
endif

ifeq ($(CONFIG_DRIVER_GAISLER_APBCTRL), defined)
subdirs += apbctrl
endif

ifeq ($(CONFIG_DRIVER_GAISLER_IRQMP), defined)
subdirs += irqmp
endif

ifeq ($(CONFIG_DRIVER_GAISLER_GPTIMER), defined)
subdirs += gptimer
endif

ifeq ($(CONFIG_DRIVER_GAISLER_GRETH), defined)
subdirs += greth
endif

