
ifeq ($(CONFIG_DRIVER_BLOCK_EMU), defined)
subdirs += block_file
endif

ifeq ($(CONFIG_DRIVER_CHAR_EMUTTY), defined)
subdirs += tty
endif

ifeq ($(CONFIG_DRIVER_ICU_EMU), defined)
subdirs += icu
endif

ifeq ($(CONFIG_DRIVER_ICU_NET_TUNTAP), defined)
subdirs += net_tuntap
endif

ifeq ($(CONFIG_DRIVER_ICU_TIMER_EMU), defined)
subdirs += timer
endif

