objs-$(CONFIG_DRIVER_PUSH_BUTTON) += push_button.o
objs-$(CONFIG_DRIVER_BUTTON_SET) += button_set.o
subdirs-$(CONFIG_DRIVER_MATRIX_KEYBOARD) += matrix_keyboard
objs-$(CONFIG_DRIVER_MTCH6102) += mtch6102.o
subdirs += sx1509_kbd
