#ifndef BLE_NET_LAYER_H_
#define BLE_NET_LAYER_H_

enum ble_net_layer_id_e {
  BLE_NET_LAYER_ADV = CONFIG_BLE_NET_LAYER_FIRST,
  BLE_NET_LAYER_MASTER,
  BLE_NET_LAYER_SLAVE,
  BLE_NET_LAYER_LINK,
  BLE_NET_LAYER_LLCP,
  BLE_NET_LAYER_L2CAP,
  BLE_NET_LAYER_SIGNALLING,
  BLE_NET_LAYER_SM,
  BLE_NET_LAYER_ATT,
  BLE_NET_LAYER_GATT,
  BLE_NET_LAYER_GATTS,
  BLE_NET_LAYER_GATTC,
  BLE_NET_LAYER_GAP,
};

#endif
