objs = \
	vfs.o \
	helpers.o \
	globals.o \
	file.o

doc_headers = vfs/file.h vfs/fs.h vfs/globals.h vfs/helpers.h vfs/ops.h vfs/types.h vfs/vfs.h

#DIR_CFLAGS=-Werror

#helpers.o_CFLAGS=-O0 -ggdb
#vfs.o_CFLAGS=-O0 -ggdb
