
DIR_CFLAGS = -D_HEXO_INTTYPES_DEPRECATED

objs = \
	file.o \
	node.o \
        path.o \
        name.o \
	fs.o

doc_headers = vfs/file.h vfs/fs.h \
vfs/defs.h vfs/ops.h vfs/node.h vfs/path.h vfs/name.h

subdirs = fs

#DIR_CFLAGS=-O0 -ggdb
#vfs.o_CFLAGS=-O0 -ggdb
