
ifeq ($(CONFIG_DRIVER_ICU_BCM2835), defined)
subdirs += bcm2835_icu
endif

ifeq ($(CONFIG_DRIVER_SYSTIMER_BCM2835), defined)
subdirs += bcm2835_systimer
endif

ifeq ($(CONFIG_DRIVER_GPIO_BCM2835), defined)
subdirs += bcm2835_gpio
endif

ifeq ($(CONFIG_DRIVER_SPI_BCM2835), defined)
subdirs += bcm2835_spi
endif
