
objs += aes.o aes_algo.o
objs-$(CONFIG_DRIVER_CRYPTO_SOFT_AES_ECB) += aes_ecb.o
objs-$(CONFIG_DRIVER_CRYPTO_SOFT_AES_CBC) += aes_cbc.o
objs-$(CONFIG_DRIVER_CRYPTO_SOFT_AES_CTR) += aes_ctr.o
objs-$(CONFIG_DRIVER_CRYPTO_SOFT_AES_OCB3) += aes_ocb.o

