subdirs-$(CONFIG_DRIVER_STM32_USART) += usart
subdirs-$(CONFIG_DRIVER_STM32_I2C) += i2c
subdirs-$(CONFIG_DRIVER_STM32_GPIO) += gpio
subdirs-$(CONFIG_DRIVER_STM32_RCC) += rcc
subdirs-$(CONFIG_DRIVER_STM32_PWM) += pwm
