BCPATH += -p $(LOCAL_SRC_DIR)
objs-$(CONFIG_BLE_CRYPTO) += sm.o sm_impl.o
objs += att.o att_encoding.o
objs += gatt.o
objs += gap.o
objs += l2cap.o link.o llcp.o
objs += signalling.o
objs += scan_filter.o
