subdirs += icu
subdirs-$(CONFIG_DRIVER_PIC32_UART) += uart
subdirs-$(CONFIG_DRIVER_PIC32_GPIO) += gpio
subdirs-$(CONFIG_DRIVER_PIC32_TIMER) += timer
subdirs-$(CONFIG_DRIVER_PIC32_SPI) += spi
subdirs-$(CONFIG_DRIVER_PIC32_DMA) += dma
