
ifeq ($(CONFIG_DRIVER_EFM32_LEUART), defined)
subdirs += leuart
endif

ifeq ($(CONFIG_DRIVER_EFM32_USART), defined)
subdirs += usart
endif

ifeq ($(CONFIG_DRIVER_EFM32_TIMER), defined)
subdirs += timer 
endif

ifeq ($(CONFIG_DRIVER_EFM32_RTC), defined)
subdirs += rtc 
endif

ifeq ($(CONFIG_DRIVER_EFM32_GPIO), defined)
subdirs += gpio
endif
