
ifeq ($(CONFIG_DRIVER_EFM32_LEUART), defined)
subdirs += leuart
endif

ifeq ($(CONFIG_DRIVER_EFM32_USART), defined)
subdirs += usart
endif

ifeq ($(CONFIG_DRIVER_EFM32_TIMER), defined)
subdirs += timer 
endif

ifeq ($(CONFIG_DRIVER_EFM32_RTC), defined)
subdirs += rtc 
endif

ifeq ($(CONFIG_DRIVER_EFM32_GPIO), defined)
subdirs += gpio
endif

ifeq ($(CONFIG_DRIVER_EFM32_I2C), defined)
subdirs += i2c
endif

ifeq ($(CONFIG_DRIVER_EFM32_RECMU), defined)
subdirs += recmu
endif

ifeq ($(CONFIG_DRIVER_EFM32_MSC), defined)
subdirs += msc
endif

