
DIR_CFLAGS = -D_HEXO_INTTYPES_DEPRECATED

objs += thread.o
objs-$(CONFIG_PTHREAD_MUTEX) += mutex.o
objs-$(CONFIG_PTHREAD_KEYS) += keys.o
objs-$(CONFIG_PTHREAD_COND) += cond.o
objs-$(CONFIG_PTHREAD_CANCEL) += cancel.o
objs-$(CONFIG_PTHREAD_BARRIER) += barrier.o
objs-$(CONFIG_PTHREAD_MAIN) += main_wrap.o

