
objs += aes.o
objs-$(CONFIG_DRIVER_EFM32_AES_ECB) += aes_ecb.o
objs-$(CONFIG_DRIVER_EFM32_AES_CBC) += aes_cbc.o
objs-$(CONFIG_DRIVER_EFM32_AES_CTR) += aes_ctr.o
objs-$(CONFIG_DRIVER_EFM32_AES_OCB3) += aes_ocb.o
objs-$(CONFIG_DRIVER_EFM32_AES_RANDOM) += aes_rand.o

