subdirs = sx1509_kbd

objs-$(CONFIG_DRIVER_PUSH_BUTTON) += push_button.o
objs-$(CONFIG_DRIVER_MTCH6102) += mtch6102.o
objs-$(CONFIG_DRIVER_ADXL345) += adxl345.o
objs-$(CONFIG_DRIVER_BUTTON_SET) += button_set.o

subdirs-$(CONFIG_DRIVER_MATRIX_KEYBOARD) += matrix_keyboard
subdirs-$(CONFIG_DRIVER_ADXL362) += adxl362
subdirs-$(CONFIG_DRIVER_MPU650X) += mpu650x
subdirs-$(CONFIG_DRIVER_PCF8563) += pcf8563
subdirs-$(CONFIG_DRIVER_DS3231) += ds3231
subdirs-$(CONFIG_DRIVER_MLX90614) += mlx90614
subdirs-$(CONFIG_DRIVER_MAX6675) += max6675
subdirs-$(CONFIG_DRIVER_HTS221) += hts221
subdirs-$(CONFIG_DRIVER_MAX44009) += max44009
subdirs-$(CONFIG_DRIVER_LPS25HB) += lps25hb
