objs-$(CONFIG_DRIVER_PUSH_BUTTON) += push_button.o
objs-$(CONFIG_DRIVER_MTCH6102) += mtch6102.o
objs-$(CONFIG_DRIVER_DS3231) += ds3231.o
objs-$(CONFIG_DRIVER_ADXL345) += adxl345.o
objs-$(CONFIG_DRIVER_ADXL362) += adxl362.o

