subdirs = sx1509_kbd led motion_sensor hwclock

objs-$(CONFIG_DRIVER_PUSH_BUTTON) += push_button.o
objs-$(CONFIG_DRIVER_MTCH6102) += mtch6102.o
objs-$(CONFIG_DRIVER_BUTTON_SET) += button_set.o

subdirs-$(CONFIG_DRIVER_MATRIX_KEYBOARD) += matrix_keyboard
subdirs-$(CONFIG_DRIVER_MLX90614) += mlx90614
subdirs-$(CONFIG_DRIVER_MAX6675) += max6675
subdirs-$(CONFIG_DRIVER_HTS221) += hts221
subdirs-$(CONFIG_DRIVER_SI2071) += si2071
subdirs-$(CONFIG_DRIVER_MAX44009) += max44009
subdirs-$(CONFIG_DRIVER_LPS25HB) += lps25hb
