/*
    This file is part of MutekH.

    MutekH is free software; you can redistribute it and/or modify it
    under the terms of the GNU Lesser General Public License as
    published by the Free Software Foundation; version 2.1 of the
    License.

    MutekH is distributed in the hope that it will be useful, but
    WITHOUT ANY WARRANTY; without even the implied warranty of
    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
    Lesser General Public License for more details.

    You should have received a copy of the GNU Lesser General Public
    License along with this program.  If not, see
    <http://www.gnu.org/licenses/>.

    Copyright (c) 2014 Nicolas Pouillon <nipo@ssji.net>
*/
#ifndef MPU6505_REGS_H_
#define MPU6505_REGS_H_

enum {
  REG_SELF_TEST_X_GYRO = 0,
  REG_SELF_TEST_Y_GYRO,
  REG_SELF_TEST_Z_GYRO,

  REG6050_XA_OFFSET_H = 6,
  REG6050_XA_OFFSET_L,
  REG6050_YA_OFFSET_H,
  REG6050_YA_OFFSET_L,
  REG6050_ZA_OFFSET_H,
  REG6050_ZA_OFFSET_L,

  REG_SELF_TEST_X_ACCEL = 13,
  REG_SELF_TEST_Y_ACCEL,
  REG_SELF_TEST_Z_ACCEL,
  REG_XG_OFFSET_H = 19,
  REG_XG_OFFSET_L,
  REG_YG_OFFSET_H,
  REG_YG_OFFSET_L,
  REG_ZG_OFFSET_H,
  REG_ZG_OFFSET_L,
  REG_SMPLRT_DIV,
  REG_CONFIG,
#define REG_CONFIG_FIFO_MODE_OVERFLOW 0x40
#define REG_CONFIG_FIFO_MODE_OVERWRITE 0x00
#define REG_CONFIG_DLPF_250HZ 0
#define REG_CONFIG_DLPF_184HZ 1
#define REG_CONFIG_DLPF_92HZ 2
#define REG_CONFIG_DLPF_41HZ 3
#define REG_CONFIG_DLPF_20HZ 4
#define REG_CONFIG_DLPF_10HZ 5
#define REG_CONFIG_DLPF_5HZ 6
#define REG_CONFIG_DLPF_3600HZ 7

  REG_GYRO_CONFIG,
#define REG_GYRO_CONFIG_X_ST_EN 0x80
#define REG_GYRO_CONFIG_Y_ST_EN 0x40
#define REG_GYRO_CONFIG_Z_ST_EN 0x20
#define REG_GYRO_CONFIG_250DPS 0
#define REG_GYRO_CONFIG_500DPS 0x80
#define REG_GYRO_CONFIG_1000DPS 0x10
#define REG_GYRO_CONFIG_2000DPS 0x18
#define REG_GYRO_CONFIG_DLPF  0x00
#define REG_GYRO_CONFIG_8800HZ 0x01
#define REG_GYRO_CONFIG_3600HZ 0x02

  REG_ACCEL_CONFIG,
#define REG_ACCEL_CONFIG_X_ST_EN 0x80
#define REG_ACCEL_CONFIG_Y_ST_EN 0x40
#define REG_ACCEL_CONFIG_Z_ST_EN 0x20
#define REG_ACCEL_CONFIG_2G 0
#define REG_ACCEL_CONFIG_4G 0x80
#define REG_ACCEL_CONFIG_8G 0x10
#define REG_ACCEL_CONFIG_16G 0x18

  REG_ACCEL_CONFIG2,
#define REG_ACCEL_CONFIG2_1_13KHZ 0x08
#define REG_ACCEL_CONFIG2_460HZ 0x0
#define REG_ACCEL_CONFIG2_184HZ 0x1
#define REG_ACCEL_CONFIG2_92HZ 0x2
#define REG_ACCEL_CONFIG2_41HZ 0x3
#define REG_ACCEL_CONFIG2_20HZ 0x4
#define REG_ACCEL_CONFIG2_10HZ 0x5
#define REG_ACCEL_CONFIG2_5HZ 0x6
#define REG_ACCEL_CONFIG2_460HZ_ 0x7

  REG_LP_ACCEL_ODR,
#define REG_LP_ACCEL_ODR_0_24HZ 0
#define REG_LP_ACCEL_ODR_0_49HZ 1
#define REG_LP_ACCEL_ODR_0_98HZ 2
#define REG_LP_ACCEL_ODR_1_95HZ 3
#define REG_LP_ACCEL_ODR_3_91HZ 4
#define REG_LP_ACCEL_ODR_7_81HZ 5
#define REG_LP_ACCEL_ODR_15_63HZ 6
#define REG_LP_ACCEL_ODR_31_65HZ 7
#define REG_LP_ACCEL_ODR_62_5HZ 8
#define REG_LP_ACCEL_ODR_125HZ 9
#define REG_LP_ACCEL_ODR_250HZ 10
#define REG_LP_ACCEL_ODR_500HZ 11

  // In 4-mg units
  REG_WOM_THR,
#define REG_WOM_THR_MG(x) ((x)/4)

  REG_FIFO_EN = 35,
#define REG_FIFO_EN_TEMP 0x80
#define REG_FIFO_EN_GYRO_X 0x40
#define REG_FIFO_EN_GYRO_Y 0x20
#define REG_FIFO_EN_GYRO_Z 0x10
#define REG_FIFO_EN_ACCEL 0x08

  REG_INT_PIN_CFG = 55,
#define REG_INT_PIN_CFG_ACTIVE_LOW 0x80
#define REG_INT_PIN_CFG_ACTIVE_HIGH 0
#define REG_INT_PIN_CFG_OPEN_DRAIN 0x40
#define REG_INT_PIN_CFG_PUSHPULL 0
#define REG_INT_PIN_CFG_LEVEL 0x20
#define REG_INT_PIN_CFG_EDGE 0
#define REG_INT_PIN_CLEAR_READ_ANY 0x10
#define REG_INT_PIN_CLEAR_READ_STATUS 0
#define REG_INT_PIN_FSYNC_IRQ_LOW 0x08
#define REG_INT_PIN_FSYNC_IRQ_HIGH 0
#define REG_INT_PIN_FSYNC_IRQ 0x04

  REG_INT_ENABLE,
#define REG_INT_ENABLE_WOM 0x40
#define REG_INT_ENABLE_FIFO_OVERFLOW 0x10
#define REG_INT_ENABLE_FSYNC 0x08
#define REG_INT_ENABLE_RAW_RDY 0x01

  REG_INT_STATUS = 58,
  REG_ACCEL_XOUT_H,
  REG_SENSOR_BLOCK_BEGIN = REG_ACCEL_XOUT_H,
  REG_ACCEL_XOUT_L,
  REG_ACCEL_YOUT_H,
  REG_ACCEL_YOUT_L,
  REG_ACCEL_ZOUT_H,
  REG_ACCEL_ZOUT_L,
  REG_TEMP_OUT_H,
  REG_TEMP_OUT_L,
  REG_GYRO_XOUT_H,
  REG_GYRO_XOUT_L,
  REG_GYRO_YOUT_H,
  REG_GYRO_YOUT_L,
  REG_GYRO_ZOUT_H,
  REG_GYRO_ZOUT_L,
  REG_SIGNAL_PATH_RESET = 104,
  REG_ACCEL_INTEL_CTRL,
#define REG_ACCEL_INTEL_EN 0x80
#define REG_ACCEL_INTEL_MODE_COMPARE 0x40
#define REG_ACCEL_INTEL_MODE_NOT_USED 0x00

  REG_USER_CTRL,
#define REG_USER_FIFO_EN 0x40
#define REG_USER_I2C_IF_DIS 0x10
#define REG_USER_FIFO_RST 0x04
#define REG_USER_SIG_COND_RST 0x01

  REG_PWR_MGMT_1,
#define REG_PWR_MGMT_1_H_RESET 0x80
#define REG_PWR_MGMT_1_SLEEP 0x40
#define REG_PWR_MGMT_1_CYCLE 0x20
#define REG_PWR_MGMT_1_GYRO_STANDBY 0x10
#define REG_PWR_MGMT_1_TEMP_DIS 0x08
#define REG_PWR_MGMT_1_CLKSTEP_INTERNAL 0
#define REG_PWR_MGMT_1_CLKSTEP_OFF 0x7

  REG_PWR_MGMT_2,
#define REG_PWR_MGMT_2_LP_WAKE_CTRL_1_25_HZ 0x00
#define REG_PWR_MGMT_2_LP_WAKE_CTRL_5_HZ 0x40
#define REG_PWR_MGMT_2_LP_WAKE_CTRL_20_HZ 0x80
#define REG_PWR_MGMT_2_LP_WAKE_CTRL_40_HZ 0xc0
#define REG_PWR_MGMT_2_DISABLE_XA 0x20
#define REG_PWR_MGMT_2_DISABLE_YA 0x10
#define REG_PWR_MGMT_2_DISABLE_ZA 0x08
#define REG_PWR_MGMT_2_DISABLE_XG 0x04
#define REG_PWR_MGMT_2_DISABLE_YG 0x02
#define REG_PWR_MGMT_2_DISABLE_ZG 0x01

  REG_FIFO_COUNT_H = 114,
  REG_FIFO_COUNT_L,
  REG_FIFO_R_W,
  REG_WHO_AM_I,
  REG_ACCEL_OFFSET = 118,
  REG_XA_OFFSET_H = 119,
  REG_XA_OFFSET_L,
  REG_YA_OFFSET_H = 122,
  REG_YA_OFFSET_L,
  REG_ZA_OFFSET_H = 125,
  REG_ZA_OFFSET_L,
};

#endif
