
ifeq ($(CONFIG_DRIVER_CHAR_SOCLIBTTY), defined)
 subdirs += tty-soclib
endif

ifeq ($(CONFIG_DRIVER_CHAR_VGATTY), defined)
 subdirs += tty-vga
endif

ifeq ($(CONFIG_DRIVER_CHAR_EMUTTY), defined)
 subdirs += tty-emu
endif

ifeq ($(CONFIG_DRIVER_CHAR_UART8250), defined)
 subdirs += uart-8250
endif

