/*
    This file is part of MutekH.

    MutekH is free software; you can redistribute it and/or modify it
    under the terms of the GNU Lesser General Public License as
    published by the Free Software Foundation; version 2.1 of the
    License.

    MutekH is distributed in the hope that it will be useful, but
    WITHOUT ANY WARRANTY; without even the implied warranty of
    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
    Lesser General Public License for more details.

    You should have received a copy of the GNU Lesser General Public
    License along with this program.  If not, see
    <http://www.gnu.org/licenses/>.

    Copyright Nicolas Pouillon <nipo@ssji.net> (c) 2015
*/

#ifndef BLE_PROTOCOL_DESCRIPTORS_H
#define BLE_PROTOCOL_DESCRIPTORS_H

#define BLE_UUID_GATT_CHARACTERISTIC_EXTENDED_PROPERTIES_DESC 0x2900
#define BLE_UUID_GATT_CHARACTERISTIC_USER_DESCRIPTION_DESC 0x2901
#define BLE_UUID_GATT_CLIENT_CHARACTERISTIC_CONFIGURATION_DESC 0x2902
#define BLE_UUID_GATT_SERVER_CHARACTERISTIC_CONFIGURATION_DESC 0x2903
#define BLE_UUID_GATT_CHARACTERISTIC_PRESENTATION_FORMAT_DESC 0x2904
#define BLE_UUID_GATT_CHARACTERISTIC_AGGREGATE_FORMAT_DESC 0x2905
#define BLE_UUID_VALID_RANGE_DESC 0x2906
#define BLE_UUID_EXTERNAL_REPORT_REFERENCE_DESC 0x2907
#define BLE_UUID_REPORT_REFERENCE_DESC 0x2908
#define BLE_UUID_ES_CONFIGURATION_DESC 0x290B
#define BLE_UUID_ES_MEASUREMENT_DESC 0x290C
#define BLE_UUID_ES_TRIGGER_SETTING_DESC 0x290D

#define BLE_GATT_PRESENTATION_(format_, exponent_, unit_, namespace_, description_) \
  {                                                                     \
    .type = BLE_UUID_SHORT_P(BLE_UUID_GATT_CHARACTERISTIC_PRESENTATION_FORMAT_DESC), \
    .data = (const uint8_t[7]){ (format_), (exponent_),                 \
                                (unit_) & 0xff, ((unit_) >> 8) & 0xff,  \
                                (namespace_),                           \
                                (description_) & 0xff,                  \
                                ((description_) >> 8) & 0xff, },        \
    .size = 7,                                                          \
  }

#define BLE_GATT_PRESENTATION(format_, exponent_, unit_, namespace_, description_)\
  BLE_GATT_PRESENTATION_(BLE_GATT_PRESENTATION_FORMAT_ ## format_,      \
                         exponent_,                                     \
                         BLE_GATT_PRESENTATION_UNIT_ ## unit_,          \
                         BLE_GATT_PRESENTATION_NAMESPACE_ ## namespace_, \
                         description_)


#define BLE_GATT_PRESENTATION_FORMAT_BOOLEAN 0x01
#define BLE_GATT_PRESENTATION_FORMAT_2BIT 0x02
#define BLE_GATT_PRESENTATION_FORMAT_NIBBLE 0x03
#define BLE_GATT_PRESENTATION_FORMAT_UINT8 0x04
#define BLE_GATT_PRESENTATION_FORMAT_UINT12 0x05
#define BLE_GATT_PRESENTATION_FORMAT_UINT16 0x06
#define BLE_GATT_PRESENTATION_FORMAT_UINT24 0x07
#define BLE_GATT_PRESENTATION_FORMAT_UINT32 0x08
#define BLE_GATT_PRESENTATION_FORMAT_UINT48 0x09
#define BLE_GATT_PRESENTATION_FORMAT_UINT64 0x0A
#define BLE_GATT_PRESENTATION_FORMAT_UINT128 0x0B
#define BLE_GATT_PRESENTATION_FORMAT_SINT8 0x0C
#define BLE_GATT_PRESENTATION_FORMAT_SINT12 0x0D
#define BLE_GATT_PRESENTATION_FORMAT_SINT16 0x0E
#define BLE_GATT_PRESENTATION_FORMAT_SINT24 0x0F
#define BLE_GATT_PRESENTATION_FORMAT_SINT32 0x10
#define BLE_GATT_PRESENTATION_FORMAT_SINT48 0x11
#define BLE_GATT_PRESENTATION_FORMAT_SINT64 0x12
#define BLE_GATT_PRESENTATION_FORMAT_SINT128 0x13
#define BLE_GATT_PRESENTATION_FORMAT_FLOAT32 0x14
#define BLE_GATT_PRESENTATION_FORMAT_FLOAT64 0x15
#define BLE_GATT_PRESENTATION_FORMAT_SFLOAT 0x16
#define BLE_GATT_PRESENTATION_FORMAT_FLOAT 0x17
#define BLE_GATT_PRESENTATION_FORMAT_DUINT16 0x18
#define BLE_GATT_PRESENTATION_FORMAT_UTF8S 0x19
#define BLE_GATT_PRESENTATION_FORMAT_UTF16S 0x1A
#define BLE_GATT_PRESENTATION_FORMAT_STRUCT 0x1B

#define BLE_GATT_PRESENTATION_UNIT_UNITLESS 0x2700
#define BLE_GATT_PRESENTATION_UNIT_LENGTH_METRE 0x2701
#define BLE_GATT_PRESENTATION_UNIT_MASS_KILOGRAM 0x2702
#define BLE_GATT_PRESENTATION_UNIT_TIME_SECOND 0x2703
#define BLE_GATT_PRESENTATION_UNIT_ELECTRIC_CURRENT_AMPERE 0x2704
#define BLE_GATT_PRESENTATION_UNIT_THERMODYNAMIC_TEMPERATURE_KELVIN 0x2705
#define BLE_GATT_PRESENTATION_UNIT_AMOUNT_OF_SUBSTANCE_MOLE 0x2706
#define BLE_GATT_PRESENTATION_UNIT_LUMINOUS_INTENSITY_CANDELA 0x2707
#define BLE_GATT_PRESENTATION_UNIT_AREA_SQUARE_METRES 0x2710
#define BLE_GATT_PRESENTATION_UNIT_VOLUME_CUBIC_METRES 0x2711
#define BLE_GATT_PRESENTATION_UNIT_VELOCITY_METRES_PER_SECOND 0x2712
#define BLE_GATT_PRESENTATION_UNIT_ACCELERATION_METRES_PER_SECOND_SQUARED 0x2713
#define BLE_GATT_PRESENTATION_UNIT_WAVENUMBER_RECIPROCAL_METRE 0x2714
#define BLE_GATT_PRESENTATION_UNIT_DENSITY_KILOGRAM_PER_CUBIC_METRE 0x2715
#define BLE_GATT_PRESENTATION_UNIT_SURFACE_DENSITY_KILOGRAM_PER_SQUARE_METRE 0x2716
#define BLE_GATT_PRESENTATION_UNIT_SPECIFIC_VOLUME_CUBIC_METRE_PER_KILOGRAM 0x2717
#define BLE_GATT_PRESENTATION_UNIT_CURRENT_DENSITY_AMPERE_PER_SQUARE_METRE 0x2718
#define BLE_GATT_PRESENTATION_UNIT_MAGNETIC_FIELD_STRENGTH_AMPERE_PER_METRE 0x2719
#define BLE_GATT_PRESENTATION_UNIT_AMOUNT_CONCENTRATION_MOLE_PER_CUBIC_METRE 0x271A
#define BLE_GATT_PRESENTATION_UNIT_MASS_CONCENTRATION_KILOGRAM_PER_CUBIC_METRE 0x271B
#define BLE_GATT_PRESENTATION_UNIT_LUMINANCE_CANDELA_PER_SQUARE_METRE 0x271C
#define BLE_GATT_PRESENTATION_UNIT_REFRACTIVE_INDEX 0x271D
#define BLE_GATT_PRESENTATION_UNIT_RELATIVE_PERMEABILITY 0x271E
#define BLE_GATT_PRESENTATION_UNIT_PLANE_ANGLE_RADIAN 0x2720
#define BLE_GATT_PRESENTATION_UNIT_SOLID_ANGLE_STERADIAN 0x2721
#define BLE_GATT_PRESENTATION_UNIT_FREQUENCY_HERTZ 0x2722
#define BLE_GATT_PRESENTATION_UNIT_FORCE_NEWTON 0x2723
#define BLE_GATT_PRESENTATION_UNIT_PRESSURE_PASCAL 0x2724
#define BLE_GATT_PRESENTATION_UNIT_ENERGY_JOULE 0x2725
#define BLE_GATT_PRESENTATION_UNIT_POWER_WATT 0x2726
#define BLE_GATT_PRESENTATION_UNIT_ELECTRIC_CHARGE_COULOMB 0x2727
#define BLE_GATT_PRESENTATION_UNIT_ELECTRIC_POTENTIAL_DIFFERENCE_VOLT 0x2728
#define BLE_GATT_PRESENTATION_UNIT_CAPACITANCE_FARAD 0x2729
#define BLE_GATT_PRESENTATION_UNIT_ELECTRIC_RESISTANCE_OHM 0x272A
#define BLE_GATT_PRESENTATION_UNIT_ELECTRIC_CONDUCTANCE_SIEMENS 0x272B
#define BLE_GATT_PRESENTATION_UNIT_MAGNETIC_FLUX_WEBER 0x272C
#define BLE_GATT_PRESENTATION_UNIT_MAGNETIC_FLUX_DENSITY_TESLA 0x272D
#define BLE_GATT_PRESENTATION_UNIT_INDUCTANCE_HENRY 0x272E
#define BLE_GATT_PRESENTATION_UNIT_THERMODYNAMIC_TEMPERATURE_DEGREE_CELSIUS 0x272F
#define BLE_GATT_PRESENTATION_UNIT_LUMINOUS_FLUX_LUMEN 0x2730
#define BLE_GATT_PRESENTATION_UNIT_ILLUMINANCE_LUX 0x2731
#define BLE_GATT_PRESENTATION_UNIT_ACTIVITY_REFERRED_TO_A_RADIONUCLIDE_BECQUEREL 0x2732
#define BLE_GATT_PRESENTATION_UNIT_ABSORBED_DOSE_GRAY 0x2733
#define BLE_GATT_PRESENTATION_UNIT_DOSE_EQUIVALENT_SIEVERT 0x2734
#define BLE_GATT_PRESENTATION_UNIT_CATALYTIC_ACTIVITY_KATAL 0x2735
#define BLE_GATT_PRESENTATION_UNIT_DYNAMIC_VISCOSITY_PASCAL_SECOND 0x2740
#define BLE_GATT_PRESENTATION_UNIT_MOMENT_OF_FORCE_NEWTON_METRE 0x2741
#define BLE_GATT_PRESENTATION_UNIT_SURFACE_TENSION_NEWTON_PER_METRE 0x2742
#define BLE_GATT_PRESENTATION_UNIT_ANGULAR_VELOCITY_RADIAN_PER_SECOND 0x2743
#define BLE_GATT_PRESENTATION_UNIT_ANGULAR_ACCELERATION_RADIAN_PER_SECOND_SQUARED 0x2744
#define BLE_GATT_PRESENTATION_UNIT_HEAT_FLUX_DENSITY_WATT_PER_SQUARE_METRE 0x2745
#define BLE_GATT_PRESENTATION_UNIT_HEAT_CAPACITY_JOULE_PER_KELVIN 0x2746
#define BLE_GATT_PRESENTATION_UNIT_SPECIFIC_HEAT_CAPACITY_JOULE_PER_KILOGRAM_KELVIN 0x2747
#define BLE_GATT_PRESENTATION_UNIT_SPECIFIC_ENERGY_JOULE_PER_KILOGRAM 0x2748
#define BLE_GATT_PRESENTATION_UNIT_THERMAL_CONDUCTIVITY_WATT_PER_METRE_KELVIN 0x2749
#define BLE_GATT_PRESENTATION_UNIT_ENERGY_DENSITY_JOULE_PER_CUBIC_METRE 0x274A
#define BLE_GATT_PRESENTATION_UNIT_ELECTRIC_FIELD_STRENGTH_VOLT_PER_METRE 0x274B
#define BLE_GATT_PRESENTATION_UNIT_ELECTRIC_CHARGE_DENSITY_COULOMB_PER_CUBIC_METRE 0x274C
#define BLE_GATT_PRESENTATION_UNIT_SURFACE_CHARGE_DENSITY_COULOMB_PER_SQUARE_METRE 0x274D
#define BLE_GATT_PRESENTATION_UNIT_ELECTRIC_FLUX_DENSITY_COULOMB_PER_SQUARE_METRE 0x274E
#define BLE_GATT_PRESENTATION_UNIT_PERMITTIVITY_FARAD_PER_METRE 0x274F
#define BLE_GATT_PRESENTATION_UNIT_PERMEABILITY_HENRY_PER_METRE 0x2750
#define BLE_GATT_PRESENTATION_UNIT_MOLAR_ENERGY_JOULE_PER_MOLE 0x2751
#define BLE_GATT_PRESENTATION_UNIT_MOLAR_ENTROPY_JOULE_PER_MOLE_KELVIN 0x2752
#define BLE_GATT_PRESENTATION_UNIT_EXPOSURE_COULOMB_PER_KILOGRAM 0x2753
#define BLE_GATT_PRESENTATION_UNIT_ABSORBED_DOSE_RATE_GRAY_PER_SECOND 0x2754
#define BLE_GATT_PRESENTATION_UNIT_RADIANT_INTENSITY_WATT_PER_STERADIAN 0x2755
#define BLE_GATT_PRESENTATION_UNIT_RADIANCE_WATT_PER_SQUARE_METRE_STERADIAN 0x2756
#define BLE_GATT_PRESENTATION_UNIT_CATALYTIC_ACTIVITY_CONCENTRATION_KATAL_PER_CUBIC_METRE 0x2757
#define BLE_GATT_PRESENTATION_UNIT_TIME_MINUTE 0x2760
#define BLE_GATT_PRESENTATION_UNIT_TIME_HOUR 0x2761
#define BLE_GATT_PRESENTATION_UNIT_TIME_DAY 0x2762
#define BLE_GATT_PRESENTATION_UNIT_PLANE_ANGLE_DEGREE 0x2763
#define BLE_GATT_PRESENTATION_UNIT_PLANE_ANGLE_MINUTE 0x2764
#define BLE_GATT_PRESENTATION_UNIT_PLANE_ANGLE_SECOND 0x2765
#define BLE_GATT_PRESENTATION_UNIT_AREA_HECTARE 0x2766
#define BLE_GATT_PRESENTATION_UNIT_VOLUME_LITRE 0x2767
#define BLE_GATT_PRESENTATION_UNIT_MASS_TONNE 0x2768
#define BLE_GATT_PRESENTATION_UNIT_PRESSURE_BAR 0x2780
#define BLE_GATT_PRESENTATION_UNIT_PRESSURE_MILLIMETRE_OF_MERCURY 0x2781
#define BLE_GATT_PRESENTATION_UNIT_LENGTH_ANGSTROM 0x2782
#define BLE_GATT_PRESENTATION_UNIT_LENGTH_NAUTICAL_MILE 0x2783
#define BLE_GATT_PRESENTATION_UNIT_AREA_BARN 0x2784
#define BLE_GATT_PRESENTATION_UNIT_VELOCITY_KNOT 0x2785
#define BLE_GATT_PRESENTATION_UNIT_LOGARITHMIC_RADIO_QUANTITY_NEPER 0x2786
#define BLE_GATT_PRESENTATION_UNIT_LOGARITHMIC_RADIO_QUANTITY_BEL 0x2787
#define BLE_GATT_PRESENTATION_UNIT_LENGTH_YARD 0x27A0
#define BLE_GATT_PRESENTATION_UNIT_LENGTH_PARSEC 0x27A1
#define BLE_GATT_PRESENTATION_UNIT_LENGTH_INCH 0x27A2
#define BLE_GATT_PRESENTATION_UNIT_LENGTH_FOOT 0x27A3
#define BLE_GATT_PRESENTATION_UNIT_LENGTH_MILE 0x27A4
#define BLE_GATT_PRESENTATION_UNIT_PRESSURE_POUND_FORCE_PER_SQUARE_INCH 0x27A5
#define BLE_GATT_PRESENTATION_UNIT_VELOCITY_KILOMETRE_PER_HOUR 0x27A6
#define BLE_GATT_PRESENTATION_UNIT_VELOCITY_MILE_PER_HOUR 0x27A7
#define BLE_GATT_PRESENTATION_UNIT_ANGULAR_VELOCITY_REVOLUTION_PER_MINUTE 0x27A8
#define BLE_GATT_PRESENTATION_UNIT_ENERGY_GRAM_CALORIE 0x27A9
#define BLE_GATT_PRESENTATION_UNIT_ENERGY_KILOGRAM_CALORIE 0x27AA
#define BLE_GATT_PRESENTATION_UNIT_ENERGY_KILOWATT_HOUR 0x27AB
#define BLE_GATT_PRESENTATION_UNIT_THERMODYNAMIC_TEMPERATURE_DEGREE_FAHRENHEIT 0x27AC
#define BLE_GATT_PRESENTATION_UNIT_PERCENTAGE 0x27AD
#define BLE_GATT_PRESENTATION_UNIT_PER_MILLE 0x27AE
#define BLE_GATT_PRESENTATION_UNIT_PERIOD_BEATS_PER_MINUTE 0x27AF
#define BLE_GATT_PRESENTATION_UNIT_ELECTRIC_CHARGE_AMPERE_HOURS 0x27B0
#define BLE_GATT_PRESENTATION_UNIT_MASS_DENSITY_MILLIGRAM_PER_DECILITRE 0x27B1
#define BLE_GATT_PRESENTATION_UNIT_MASS_DENSITY_MILLIMOLE_PER_LITRE 0x27B2
#define BLE_GATT_PRESENTATION_UNIT_TIME_YEAR 0x27B3
#define BLE_GATT_PRESENTATION_UNIT_TIME_MONTH 0x27B4
#define BLE_GATT_PRESENTATION_UNIT_CONCENTRATION_COUNT_PER_CUBIC_METRE 0x27B5
#define BLE_GATT_PRESENTATION_UNIT_IRRADIANCE_WATT_PER_SQUARE_METRE 0x27B6
#define BLE_GATT_PRESENTATION_UNIT_MILLILITER_PER_KILOGRAM_PER_MINUTE 0x27B7
#define BLE_GATT_PRESENTATION_UNIT_MASS_POUND 0x27B8

#define BLE_GATT_PRESENTATION_NAMESPACE_SIG 0x01

#endif
