subdirs-$(CONFIG_DRIVER_SOCLIB_BLOCK_DEVICE) += block
subdirs-$(CONFIG_DRIVER_SOCLIB_ICU) += icu
subdirs-$(CONFIG_DRIVER_SOCLIB_MULTI_TTY) += multi_tty
subdirs-$(CONFIG_DRIVER_SOCLIB_TIMER) += timer
subdirs-$(CONFIG_DRIVER_SOCLIB_XICU) += xicu
subdirs-$(CONFIG_DRIVER_SOCLIB_ETHERNET) += ethernet
subdirs-$(CONFIG_DRIVER_SOCLIB_SPI) += spi
subdirs-$(CONFIG_DRIVER_SOCLIB_RFPACKET) += rfpacket
