
OBJ-y += libnetwork/protocols/ether.o
OBJ-y += libnetwork/protocols/dummy.o
#OBJ-y += libnetwork/protocols/arp.o
#OBJ-y += libnetwork/protocols/ip.o
#OBJ-y += libnetwork/protocols/icmp.o
#OBJ-y += libnetwork/protocols/udp.o


