
ifeq ($(CONFIG_DRIVER_NET_NE2000), defined)
 subdirs += ne2000
endif

ifeq ($(CONFIG_DRIVER_NET_TUNTAP), defined)
 subdirs += tuntap
endif

ifeq ($(CONFIG_DRIVER_NET_3C900), defined)
 subdirs += 3c900
endif

