
subdirs-$(CONFIG_DRIVER_CRYPTO_SOFT_ARC4) += soft_arc4
subdirs-$(CONFIG_DRIVER_CRYPTO_SOFT_AES) += soft_aes

subdirs-$(CONFIG_DRIVER_CRYPTO_SOFT_MD5) += soft_md5
subdirs-$(CONFIG_DRIVER_CRYPTO_SOFT_SHA1) += soft_sha1
subdirs-$(CONFIG_DRIVER_CRYPTO_SOFT_SHA2) += soft_sha2

