/***************************************
* Auto generated by BFGen, do not edit *
***************************************/

/*
   bfgen -o cdefs cdefs_use_reg_mask=1 cdefs_use_field_set=1                   \
     reg_prefix=STM32 field_prefix=STM32 cdefs_use_field_mask=1        \
     cdefs_use_field_get=1
*/

#ifndef _EXTI_BFGEN_DEFS_
#define _EXTI_BFGEN_DEFS_

#define STM32_EXTI_IMR_ADDR                      0x00000000
#define STM32_EXTI_IMR_MASK                      0x0000ffff
  #define STM32_EXTI_IMR_MR_MASK               0x00000001
  #define STM32_EXTI_IMR_MR_COUNT              16
  #define STM32_EXTI_IMR_MR(fidx)              (0x00000001 << ((fidx)))
  #define STM32_EXTI_IMR_MR_SET(fidx, x, v)    do { (x) = (((x) & ~(0x1 << ((fidx)))) | ((v) << ((fidx) + 0))); } while(0)
  #define STM32_EXTI_IMR_MR_GET(fidx, x)       (((x) >> ((fidx) + 0)) & 0x1)
  #define STM32_EXTI_IMR_MR16_MASK             0x00000001
  #define STM32_EXTI_IMR_MR16                  0x00000002
  #define STM32_EXTI_IMR_MR16_SET(x, v)        do { (x) = (((x) & ~0x2) | ((v) << 1)); } while(0)
  #define STM32_EXTI_IMR_MR16_GET(x)           (((x) >> 1) & 0x1)
  #define STM32_EXTI_IMR_MR17_MASK             0x00000001
  #define STM32_EXTI_IMR_MR17                  0x00000004
  #define STM32_EXTI_IMR_MR17_SET(x, v)        do { (x) = (((x) & ~0x4) | ((v) << 2)); } while(0)
  #define STM32_EXTI_IMR_MR17_GET(x)           (((x) >> 2) & 0x1)
  #define STM32_EXTI_IMR_MR18_MASK             0x00000001
  #define STM32_EXTI_IMR_MR18                  0x00000008
  #define STM32_EXTI_IMR_MR18_SET(x, v)        do { (x) = (((x) & ~0x8) | ((v) << 3)); } while(0)
  #define STM32_EXTI_IMR_MR18_GET(x)           (((x) >> 3) & 0x1)
  #define STM32_EXTI_IMR_MR21_MASK             0x00000001
  #define STM32_EXTI_IMR_MR21                  0x00000040
  #define STM32_EXTI_IMR_MR21_SET(x, v)        do { (x) = (((x) & ~0x40) | ((v) << 6)); } while(0)
  #define STM32_EXTI_IMR_MR21_GET(x)           (((x) >> 6) & 0x1)
  #define STM32_EXTI_IMR_MR22_MASK             0x00000001
  #define STM32_EXTI_IMR_MR22                  0x00000080
  #define STM32_EXTI_IMR_MR22_SET(x, v)        do { (x) = (((x) & ~0x80) | ((v) << 7)); } while(0)
  #define STM32_EXTI_IMR_MR22_GET(x)           (((x) >> 7) & 0x1)

#define STM32_EXTI_EMR_ADDR                      0x00000004
#define STM32_EXTI_EMR_MASK                      0x0000ffff
  #define STM32_EXTI_EMR_MR_MASK               0x00000001
  #define STM32_EXTI_EMR_MR_COUNT              16
  #define STM32_EXTI_EMR_MR(fidx)              (0x00000001 << ((fidx)))
  #define STM32_EXTI_EMR_MR_SET(fidx, x, v)    do { (x) = (((x) & ~(0x1 << ((fidx)))) | ((v) << ((fidx) + 0))); } while(0)
  #define STM32_EXTI_EMR_MR_GET(fidx, x)       (((x) >> ((fidx) + 0)) & 0x1)
  #define STM32_EXTI_EMR_MR16_MASK             0x00000001
  #define STM32_EXTI_EMR_MR16                  0x00000002
  #define STM32_EXTI_EMR_MR16_SET(x, v)        do { (x) = (((x) & ~0x2) | ((v) << 1)); } while(0)
  #define STM32_EXTI_EMR_MR16_GET(x)           (((x) >> 1) & 0x1)
  #define STM32_EXTI_EMR_MR17_MASK             0x00000001
  #define STM32_EXTI_EMR_MR17                  0x00000004
  #define STM32_EXTI_EMR_MR17_SET(x, v)        do { (x) = (((x) & ~0x4) | ((v) << 2)); } while(0)
  #define STM32_EXTI_EMR_MR17_GET(x)           (((x) >> 2) & 0x1)
  #define STM32_EXTI_EMR_MR18_MASK             0x00000001
  #define STM32_EXTI_EMR_MR18                  0x00000008
  #define STM32_EXTI_EMR_MR18_SET(x, v)        do { (x) = (((x) & ~0x8) | ((v) << 3)); } while(0)
  #define STM32_EXTI_EMR_MR18_GET(x)           (((x) >> 3) & 0x1)
  #define STM32_EXTI_EMR_MR21_MASK             0x00000001
  #define STM32_EXTI_EMR_MR21                  0x00000040
  #define STM32_EXTI_EMR_MR21_SET(x, v)        do { (x) = (((x) & ~0x40) | ((v) << 6)); } while(0)
  #define STM32_EXTI_EMR_MR21_GET(x)           (((x) >> 6) & 0x1)
  #define STM32_EXTI_EMR_MR22_MASK             0x00000001
  #define STM32_EXTI_EMR_MR22                  0x00000080
  #define STM32_EXTI_EMR_MR22_SET(x, v)        do { (x) = (((x) & ~0x80) | ((v) << 7)); } while(0)
  #define STM32_EXTI_EMR_MR22_GET(x)           (((x) >> 7) & 0x1)

#define STM32_EXTI_RTSR_ADDR                     0x00000008
#define STM32_EXTI_RTSR_MASK                     0x0000ffff
  #define STM32_EXTI_RTSR_TR_MASK              0x00000001
  #define STM32_EXTI_RTSR_TR_COUNT             16
  #define STM32_EXTI_RTSR_TR(fidx)             (0x00000001 << ((fidx)))
  #define STM32_EXTI_RTSR_TR_SET(fidx, x, v)   do { (x) = (((x) & ~(0x1 << ((fidx)))) | ((v) << ((fidx) + 0))); } while(0)
  #define STM32_EXTI_RTSR_TR_GET(fidx, x)      (((x) >> ((fidx) + 0)) & 0x1)
  #define STM32_EXTI_RTSR_TR16_MASK            0x00000001
  #define STM32_EXTI_RTSR_TR16                 0x00000002
  #define STM32_EXTI_RTSR_TR16_SET(x, v)       do { (x) = (((x) & ~0x2) | ((v) << 1)); } while(0)
  #define STM32_EXTI_RTSR_TR16_GET(x)          (((x) >> 1) & 0x1)
  #define STM32_EXTI_RTSR_TR17_MASK            0x00000001
  #define STM32_EXTI_RTSR_TR17                 0x00000004
  #define STM32_EXTI_RTSR_TR17_SET(x, v)       do { (x) = (((x) & ~0x4) | ((v) << 2)); } while(0)
  #define STM32_EXTI_RTSR_TR17_GET(x)          (((x) >> 2) & 0x1)
  #define STM32_EXTI_RTSR_TR18_MASK            0x00000001
  #define STM32_EXTI_RTSR_TR18                 0x00000008
  #define STM32_EXTI_RTSR_TR18_SET(x, v)       do { (x) = (((x) & ~0x8) | ((v) << 3)); } while(0)
  #define STM32_EXTI_RTSR_TR18_GET(x)          (((x) >> 3) & 0x1)
  #define STM32_EXTI_RTSR_TR21_MASK            0x00000001
  #define STM32_EXTI_RTSR_TR21                 0x00000040
  #define STM32_EXTI_RTSR_TR21_SET(x, v)       do { (x) = (((x) & ~0x40) | ((v) << 6)); } while(0)
  #define STM32_EXTI_RTSR_TR21_GET(x)          (((x) >> 6) & 0x1)
  #define STM32_EXTI_RTSR_TR22_MASK            0x00000001
  #define STM32_EXTI_RTSR_TR22                 0x00000080
  #define STM32_EXTI_RTSR_TR22_SET(x, v)       do { (x) = (((x) & ~0x80) | ((v) << 7)); } while(0)
  #define STM32_EXTI_RTSR_TR22_GET(x)          (((x) >> 7) & 0x1)

#define STM32_EXTI_FTSR_ADDR                     0x0000000c
#define STM32_EXTI_FTSR_MASK                     0x0000ffff
  #define STM32_EXTI_FTSR_TR_MASK              0x00000001
  #define STM32_EXTI_FTSR_TR_COUNT             16
  #define STM32_EXTI_FTSR_TR(fidx)             (0x00000001 << ((fidx)))
  #define STM32_EXTI_FTSR_TR_SET(fidx, x, v)   do { (x) = (((x) & ~(0x1 << ((fidx)))) | ((v) << ((fidx) + 0))); } while(0)
  #define STM32_EXTI_FTSR_TR_GET(fidx, x)      (((x) >> ((fidx) + 0)) & 0x1)
  #define STM32_EXTI_FTSR_TR16_MASK            0x00000001
  #define STM32_EXTI_FTSR_TR16                 0x00000002
  #define STM32_EXTI_FTSR_TR16_SET(x, v)       do { (x) = (((x) & ~0x2) | ((v) << 1)); } while(0)
  #define STM32_EXTI_FTSR_TR16_GET(x)          (((x) >> 1) & 0x1)
  #define STM32_EXTI_FTSR_TR17_MASK            0x00000001
  #define STM32_EXTI_FTSR_TR17                 0x00000004
  #define STM32_EXTI_FTSR_TR17_SET(x, v)       do { (x) = (((x) & ~0x4) | ((v) << 2)); } while(0)
  #define STM32_EXTI_FTSR_TR17_GET(x)          (((x) >> 2) & 0x1)
  #define STM32_EXTI_FTSR_TR18_MASK            0x00000001
  #define STM32_EXTI_FTSR_TR18                 0x00000008
  #define STM32_EXTI_FTSR_TR18_SET(x, v)       do { (x) = (((x) & ~0x8) | ((v) << 3)); } while(0)
  #define STM32_EXTI_FTSR_TR18_GET(x)          (((x) >> 3) & 0x1)
  #define STM32_EXTI_FTSR_TR21_MASK            0x00000001
  #define STM32_EXTI_FTSR_TR21                 0x00000040
  #define STM32_EXTI_FTSR_TR21_SET(x, v)       do { (x) = (((x) & ~0x40) | ((v) << 6)); } while(0)
  #define STM32_EXTI_FTSR_TR21_GET(x)          (((x) >> 6) & 0x1)
  #define STM32_EXTI_FTSR_TR22_MASK            0x00000001
  #define STM32_EXTI_FTSR_TR22                 0x00000080
  #define STM32_EXTI_FTSR_TR22_SET(x, v)       do { (x) = (((x) & ~0x80) | ((v) << 7)); } while(0)
  #define STM32_EXTI_FTSR_TR22_GET(x)          (((x) >> 7) & 0x1)

#define STM32_EXTI_SWIER_ADDR                    0x00000010
#define STM32_EXTI_SWIER_MASK                    0x0000ffff
  #define STM32_EXTI_SWIER_TR_MASK             0x00000001
  #define STM32_EXTI_SWIER_TR_COUNT            16
  #define STM32_EXTI_SWIER_TR(fidx)            (0x00000001 << ((fidx)))
  #define STM32_EXTI_SWIER_TR_SET(fidx, x, v)  do { (x) = (((x) & ~(0x1 << ((fidx)))) | ((v) << ((fidx) + 0))); } while(0)
  #define STM32_EXTI_SWIER_TR_GET(fidx, x)     (((x) >> ((fidx) + 0)) & 0x1)
  #define STM32_EXTI_SWIER_TR16_MASK           0x00000001
  #define STM32_EXTI_SWIER_TR16                0x00000002
  #define STM32_EXTI_SWIER_TR16_SET(x, v)      do { (x) = (((x) & ~0x2) | ((v) << 1)); } while(0)
  #define STM32_EXTI_SWIER_TR16_GET(x)         (((x) >> 1) & 0x1)
  #define STM32_EXTI_SWIER_TR17_MASK           0x00000001
  #define STM32_EXTI_SWIER_TR17                0x00000004
  #define STM32_EXTI_SWIER_TR17_SET(x, v)      do { (x) = (((x) & ~0x4) | ((v) << 2)); } while(0)
  #define STM32_EXTI_SWIER_TR17_GET(x)         (((x) >> 2) & 0x1)
  #define STM32_EXTI_SWIER_TR18_MASK           0x00000001
  #define STM32_EXTI_SWIER_TR18                0x00000008
  #define STM32_EXTI_SWIER_TR18_SET(x, v)      do { (x) = (((x) & ~0x8) | ((v) << 3)); } while(0)
  #define STM32_EXTI_SWIER_TR18_GET(x)         (((x) >> 3) & 0x1)
  #define STM32_EXTI_SWIER_TR21_MASK           0x00000001
  #define STM32_EXTI_SWIER_TR21                0x00000040
  #define STM32_EXTI_SWIER_TR21_SET(x, v)      do { (x) = (((x) & ~0x40) | ((v) << 6)); } while(0)
  #define STM32_EXTI_SWIER_TR21_GET(x)         (((x) >> 6) & 0x1)
  #define STM32_EXTI_SWIER_TR22_MASK           0x00000001
  #define STM32_EXTI_SWIER_TR22                0x00000080
  #define STM32_EXTI_SWIER_TR22_SET(x, v)      do { (x) = (((x) & ~0x80) | ((v) << 7)); } while(0)
  #define STM32_EXTI_SWIER_TR22_GET(x)         (((x) >> 7) & 0x1)

#define STM32_EXTI_PR_ADDR                       0x00000014
#define STM32_EXTI_PR_MASK                       0x0000ffff
  #define STM32_EXTI_PR_PR_MASK                0x00000001
  #define STM32_EXTI_PR_PR_COUNT               16
  #define STM32_EXTI_PR_PR(fidx)               (0x00000001 << ((fidx)))
  #define STM32_EXTI_PR_PR_SET(fidx, x, v)     do { (x) = (((x) & ~(0x1 << ((fidx)))) | ((v) << ((fidx) + 0))); } while(0)
  #define STM32_EXTI_PR_PR_GET(fidx, x)        (((x) >> ((fidx) + 0)) & 0x1)
  #define STM32_EXTI_PR_PR16_MASK              0x00000001
  #define STM32_EXTI_PR_PR16                   0x00000002
  #define STM32_EXTI_PR_PR16_SET(x, v)         do { (x) = (((x) & ~0x2) | ((v) << 1)); } while(0)
  #define STM32_EXTI_PR_PR16_GET(x)            (((x) >> 1) & 0x1)
  #define STM32_EXTI_PR_PR17_MASK              0x00000001
  #define STM32_EXTI_PR_PR17                   0x00000004
  #define STM32_EXTI_PR_PR17_SET(x, v)         do { (x) = (((x) & ~0x4) | ((v) << 2)); } while(0)
  #define STM32_EXTI_PR_PR17_GET(x)            (((x) >> 2) & 0x1)
  #define STM32_EXTI_PR_PR18_MASK              0x00000001
  #define STM32_EXTI_PR_PR18                   0x00000008
  #define STM32_EXTI_PR_PR18_SET(x, v)         do { (x) = (((x) & ~0x8) | ((v) << 3)); } while(0)
  #define STM32_EXTI_PR_PR18_GET(x)            (((x) >> 3) & 0x1)
  #define STM32_EXTI_PR_PR21_MASK              0x00000001
  #define STM32_EXTI_PR_PR21                   0x00000040
  #define STM32_EXTI_PR_PR21_SET(x, v)         do { (x) = (((x) & ~0x40) | ((v) << 6)); } while(0)
  #define STM32_EXTI_PR_PR21_GET(x)            (((x) >> 6) & 0x1)
  #define STM32_EXTI_PR_PR22_MASK              0x00000001
  #define STM32_EXTI_PR_PR22                   0x00000080
  #define STM32_EXTI_PR_PR22_SET(x, v)         do { (x) = (((x) & ~0x80) | ((v) << 7)); } while(0)
  #define STM32_EXTI_PR_PR22_GET(x)            (((x) >> 7) & 0x1)

#endif

