#!/bin/bash

if [ "$#" -eq 0 ] ; then
   echo "Usage: $0 <some command>"
   echo
   echo "Execute a command with terminal in raw mode"
   exit 1
fi

trap "stty icanon echo brkint icrnl -ixoff imaxbel iutf8" EXIT
stty -icanon -echo -brkint -icrnl ixoff -imaxbel iutf8
$*
