/***************************************
* Auto generated by BFGen, do not edit *
***************************************/

/*
   bfgen -o cdefs -O arch/pic32/include/arch/pic32_irq.h cdefs_use_reg_mask=1  \
     cdefs_use_field_setval=1 -I /opt/bfgen/defs/pic32/pic32_icu.bf
*/

#ifndef _PIC32_ICU_BFGEN_DEFS_
#define _PIC32_ICU_BFGEN_DEFS_

#define PIC32_ICU_INTCON_ADDR                        0x00000000
#define PIC32_ICU_INTCON_MASK                        0x0000171f
  #define PIC32_ICU_INTCON_INTEP_COUNT             5
  #define PIC32_ICU_INTCON_INTEP(fidx, v)          ((PIC32_ICU_INTCON_INTEP_##v) << ((fidx) + 0))
  #define PIC32_ICU_INTCON_INTEP_SET(fidx, x, v)   do { (x) = (((x) & ~(0x1 << ((fidx)))) | ((PIC32_ICU_INTCON_INTEP_##v) << ((fidx) + 0))); } while(0)
  #define PIC32_ICU_INTCON_INTEP_SETVAL(fidx, x, v) do { (x) = (((x) & ~(0x1 << ((fidx)))) | ((v) << ((fidx) + 0))); } while(0)
  #define PIC32_ICU_INTCON_INTEP_GET(fidx, x)      (((x) >> ((fidx) + 0)) & 0x1)
  #define PIC32_ICU_INTCON_INTEP_FALLING           0x00000000
  #define PIC32_ICU_INTCON_INTEP_RISING            0x00000001
  #define PIC32_ICU_INTCON_TPC(v)                  ((v) << 8)
  #define PIC32_ICU_INTCON_TPC_SET(x, v)           do { (x) = (((x) & ~0x700) | ((v) << 8)); } while(0)
  #define PIC32_ICU_INTCON_TPC_GET(x)              (((x) >> 8) & 0x7)
  #define PIC32_ICU_INTCON_MVEC                    0x00001000

#define PIC32_ICU_PRISS_ADDR                         0x00000010
#define PIC32_ICU_PRISS_MASK                         0xfffffff1
  #define PIC32_ICU_PRISS_SS0                      0x00000001
  #define PIC32_ICU_PRISS_PRISS_COUNT              7
  #define PIC32_ICU_PRISS_PRISS(fidx, v)           ((v) << ((fidx) * 4 + 4))
  #define PIC32_ICU_PRISS_PRISS_SET(fidx, x, v)    do { (x) = (((x) & ~(0xf0 << ((fidx) * 4))) | ((v) << ((fidx) * 4 + 4))); } while(0)
  #define PIC32_ICU_PRISS_PRISS_GET(fidx, x)       (((x) >> ((fidx) * 4 + 4)) & 0xf)

#define PIC32_ICU_INTSTAT_ADDR                       0x00000020
#define PIC32_ICU_INTSTAT_MASK                       0x000007ff
  #define PIC32_ICU_INTSTAT_SIRQ(v)                ((v) << 0)
  #define PIC32_ICU_INTSTAT_SIRQ_SET(x, v)         do { (x) = (((x) & ~0xff) | ((v) << 0)); } while(0)
  #define PIC32_ICU_INTSTAT_SIRQ_GET(x)            (((x) >> 0) & 0xff)
  #define PIC32_ICU_INTSTAT_SRIPL(v)               ((v) << 8)
  #define PIC32_ICU_INTSTAT_SRIPL_SET(x, v)        do { (x) = (((x) & ~0x700) | ((v) << 8)); } while(0)
  #define PIC32_ICU_INTSTAT_SRIPL_GET(x)           (((x) >> 8) & 0x7)

#define PIC32_ICU_IPTMR_ADDR                         0x00000030
#define PIC32_ICU_IPTMR_MASK                         0xffffffff
  #define PIC32_ICU_IPTMR_RELOAD(v)                ((v) << 0)
  #define PIC32_ICU_IPTMR_RELOAD_SET(x, v)         do { (x) = (((x) & ~0xffffffff) | ((v) << 0)); } while(0)
  #define PIC32_ICU_IPTMR_RELOAD_GET(x)            (((x) >> 0) & 0xffffffff)

#define PIC32_ICU_IFS_ADDR(ridx)                     (0x00000040 + (ridx) * 16)
#define PIC32_ICU_IFS_COUNT                          6
#define PIC32_ICU_IFS_MASK                           0xffffffff
  #define PIC32_ICU_IFS_IRQ_COUNT                  32
  #define PIC32_ICU_IFS_IRQ(fidx)                  (0x00000001 << ((fidx)))

#define PIC32_ICU_IFS_CLR_ADDR(ridx)                 (0x00000044 + (ridx) * 16)
#define PIC32_ICU_IFS_CLR_COUNT                      6
#define PIC32_ICU_IFS_CLR_MASK                       0xffffffff
  #define PIC32_ICU_IFS_CLR_EN_COUNT               32
  #define PIC32_ICU_IFS_CLR_EN(fidx)               (0x00000001 << ((fidx)))

#define PIC32_ICU_IFS_SET_ADDR(ridx)                 (0x00000048 + (ridx) * 16)
#define PIC32_ICU_IFS_SET_COUNT                      6
#define PIC32_ICU_IFS_SET_MASK                       0xffffffff
  #define PIC32_ICU_IFS_SET_EN_COUNT               32
  #define PIC32_ICU_IFS_SET_EN(fidx)               (0x00000001 << ((fidx)))

#define PIC32_ICU_IEC_ADDR(ridx)                     (0x000000c0 + (ridx) * 16)
#define PIC32_ICU_IEC_COUNT                          6
#define PIC32_ICU_IEC_MASK                           0xffffffff
  #define PIC32_ICU_IEC_EN_COUNT                   32
  #define PIC32_ICU_IEC_EN(fidx)                   (0x00000001 << ((fidx)))

#define PIC32_ICU_IEC_CLR_ADDR(ridx)                 (0x000000c4 + (ridx) * 16)
#define PIC32_ICU_IEC_CLR_COUNT                      6
#define PIC32_ICU_IEC_CLR_MASK                       0xffffffff
  #define PIC32_ICU_IEC_CLR_EN_COUNT               32
  #define PIC32_ICU_IEC_CLR_EN(fidx)               (0x00000001 << ((fidx)))

#define PIC32_ICU_IEC_SET_ADDR(ridx)                 (0x000000c8 + (ridx) * 16)
#define PIC32_ICU_IEC_SET_COUNT                      6
#define PIC32_ICU_IEC_SET_MASK                       0xffffffff
  #define PIC32_ICU_IEC_SET_EN_COUNT               32
  #define PIC32_ICU_IEC_SET_EN(fidx)               (0x00000001 << ((fidx)))

#define PIC32_ICU_IPC_ADDR(ridx)                     (0x00000140 + (ridx) * 16)
#define PIC32_ICU_IPC_COUNT                          48
#define PIC32_ICU_IPC_MASK                           0x1f1f1f1f
  #define PIC32_ICU_IPC_IS_COUNT                   4
  #define PIC32_ICU_IPC_IS(fidx, v)                ((v) << ((fidx) * 8 + 0))
  #define PIC32_ICU_IPC_IS_SET(fidx, x, v)         do { (x) = (((x) & ~(0x3 << ((fidx) * 8))) | ((v) << ((fidx) * 8 + 0))); } while(0)
  #define PIC32_ICU_IPC_IS_GET(fidx, x)            (((x) >> ((fidx) * 8 + 0)) & 0x3)
  #define PIC32_ICU_IPC_IP_COUNT                   4
  #define PIC32_ICU_IPC_IP(fidx, v)                ((v) << ((fidx) * 8 + 2))
  #define PIC32_ICU_IPC_IP_SET(fidx, x, v)         do { (x) = (((x) & ~(0x1c << ((fidx) * 8))) | ((v) << ((fidx) * 8 + 2))); } while(0)
  #define PIC32_ICU_IPC_IP_GET(fidx, x)            (((x) >> ((fidx) * 8 + 2)) & 0x7)

#define PIC32_ICU_OFF_ADDR(ridx)                     (0x00000540 + (ridx) * 4)
#define PIC32_ICU_OFF_COUNT                          191
#define PIC32_ICU_OFF_MASK                           0x0003fffe
  #define PIC32_ICU_OFF_VAL(v)                     ((v) << 1)
  #define PIC32_ICU_OFF_VAL_SET(x, v)              do { (x) = (((x) & ~0x3fffe) | ((v) << 1)); } while(0)
  #define PIC32_ICU_OFF_VAL_GET(x)                 (((x) >> 1) & 0x1ffff)

#endif

