/***************************************
* Auto generated by BFGen, do not edit *
***************************************/

/*
   bfgen -o cdefs -O arch/pic32/include/arch/pic32_timer.h cdefs_use_reg_mask=1 \
     cdefs_use_field_setval=1 -I /opt/bfgen/defs/pic32/pic32_timer.bf
*/

#ifndef _PIC32_TIMER_BFGEN_DEFS_
#define _PIC32_TIMER_BFGEN_DEFS_

#define PIC32_TIMER_CON_ADDR                         0x00000000
#define PIC32_TIMER_CON_MASK                         0x0000a0fa
  #define PIC32_TIMER_CON_TCS(v)                   ((PIC32_TIMER_CON_TCS_##v) << 1)
  #define PIC32_TIMER_CON_TCS_SET(x, v)            do { (x) = (((x) & ~0x2) | ((PIC32_TIMER_CON_TCS_##v) << 1)); } while(0)
  #define PIC32_TIMER_CON_TCS_SETVAL(x, v)         do { (x) = (((x) & ~0x2) | ((v) << 1)); } while(0)
  #define PIC32_TIMER_CON_TCS_GET(x)               (((x) >> 1) & 0x1)
    #define PIC32_TIMER_CON_TCS_INTERNAL             0x00000000
    #define PIC32_TIMER_CON_TCS_EXTERNAL             0x00000001
  #define PIC32_TIMER_CON_T32                      0x00000008
  #define PIC32_TIMER_CON_TCKPS(v)                 ((PIC32_TIMER_CON_TCKPS_##v) << 4)
  #define PIC32_TIMER_CON_TCKPS_SET(x, v)          do { (x) = (((x) & ~0x70) | ((PIC32_TIMER_CON_TCKPS_##v) << 4)); } while(0)
  #define PIC32_TIMER_CON_TCKPS_SETVAL(x, v)       do { (x) = (((x) & ~0x70) | ((v) << 4)); } while(0)
  #define PIC32_TIMER_CON_TCKPS_GET(x)             (((x) >> 4) & 0x7)
    #define PIC32_TIMER_CON_TCKPS_DIV1               0x00000000
    #define PIC32_TIMER_CON_TCKPS_DIV2               0x00000001
    #define PIC32_TIMER_CON_TCKPS_DIV4               0x00000002
    #define PIC32_TIMER_CON_TCKPS_DIV8               0x00000003
    #define PIC32_TIMER_CON_TCKPS_DIV16              0x00000004
    #define PIC32_TIMER_CON_TCKPS_DIV32              0x00000005
    #define PIC32_TIMER_CON_TCKPS_DIV64              0x00000006
    #define PIC32_TIMER_CON_TCKPS_DIV256             0x00000007
  #define PIC32_TIMER_CON_TGATE                    0x00000080
  #define PIC32_TIMER_CON_SIDL                     0x00002000
  #define PIC32_TIMER_CON_ON                       0x00008000

#define PIC32_TIMER_CON_CLR_ADDR                     0x00000004
#define PIC32_TIMER_CON_CLR_MASK                     0x0000a0fa
  #define PIC32_TIMER_CON_CLR_TCS                  0x00000002
  #define PIC32_TIMER_CON_CLR_T32                  0x00000008
  #define PIC32_TIMER_CON_CLR_TCKPS(v)             ((v) << 4)
  #define PIC32_TIMER_CON_CLR_TCKPS_SET(x, v)      do { (x) = (((x) & ~0x70) | ((v) << 4)); } while(0)
  #define PIC32_TIMER_CON_CLR_TCKPS_GET(x)         (((x) >> 4) & 0x7)
  #define PIC32_TIMER_CON_CLR_TGATE                0x00000080
  #define PIC32_TIMER_CON_CLR_SIDL                 0x00002000
  #define PIC32_TIMER_CON_CLR_ON                   0x00008000

#define PIC32_TIMER_TMR_ADDR                         0x00000010
#define PIC32_TIMER_TMR_MASK                         0xffffffff
  #define PIC32_TIMER_TMR_VAL(v)                   ((v) << 0)
  #define PIC32_TIMER_TMR_VAL_SET(x, v)            do { (x) = (((x) & ~0xffffffff) | ((v) << 0)); } while(0)
  #define PIC32_TIMER_TMR_VAL_GET(x)               (((x) >> 0) & 0xffffffff)

#define PIC32_TIMER_PR_ADDR                          0x00000020
#define PIC32_TIMER_PR_MASK                          0xffffffff
  #define PIC32_TIMER_PR_VAL(v)                    ((v) << 0)
  #define PIC32_TIMER_PR_VAL_SET(x, v)             do { (x) = (((x) & ~0xffffffff) | ((v) << 0)); } while(0)
  #define PIC32_TIMER_PR_VAL_GET(x)                (((x) >> 0) & 0xffffffff)

#endif

