
ifeq ($(CONFIG_DRIVER_BLOCK_RAMDISK), defined)
 subdirs += ramdisk
endif

ifeq ($(CONFIG_DRIVER_BLOCK_PARTITION), defined)
 subdirs += partition
endif

ifeq ($(CONFIG_DRIVER_BLOCK_CACHE), defined)
 subdirs += cache
endif

ifeq ($(CONFIG_DRIVER_BLOCK_SD_MMC), defined)
 subdirs += sd-mmc
endif
