objs += radio.o uuid.o
subdirs += protocol net stack
subdirs-$(CONFIG_PERIPHERAL) += beacon
subdirs-$(CONFIG_BLE_GATT) += gatt
objs-$(CONFIG_BLE_CRYPTO) += crypto.o
objs-$(CONFIG_BLE_SECURITY_DB) += security_db.o
