objs += radio.o uuid.o
subdirs += protocol net stack util
subdirs-$(CONFIG_BLE_GATTDB) += gattdb
subdirs-$(CONFIG_BLE_GATTC) += gattc
subdirs += profile
objs-$(CONFIG_BLE_CRYPTO) += crypto.o security_db.o
objs += peer.o

enum_headers = include/ble/profile/fluke/measurement.h
